env: "local"
server:
  host: "localhost"
  port: "8080"

logger:
  mode: "local"
  disable_src: true
  file_path: "/stat/log/blog.log"

sqlite:
  path: "file:storage/blog.db?_foreign_keys=on"

redis:
  addr: "0.0.0.0:6379"
  password: "s3cr3tP@ssw0rd"
  username: "admin"

frontend:
  static_files:
    root: "static"
    css: "static/css"
    js: "static/js"
  templates:
    root: "templates/"

auth:
  secret_key: "01234567890123456789012345678912"
