# Generated by Django 5.0.1 on 2025-05-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='none title', max_length=124),
        ),
    ]
