# Generated by Django 5.0.1 on 2025-05-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='description',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
    ]
